# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    # 1. إظهار تحذير عند عدم استخدام const مع الـ Constructors التي تقبل const
    prefer_const_constructors: true

    # 2. إظهار تحذير إذا نسيت const قبل الـ Widgets الفرعية في القوائم (مثل Children)
    prefer_const_constructors_in_immutables: true

    # 3. إظهار تحذير لإضافة const على اللفظ الضمني (مثل List/Map/Set الثابتة)
    prefer_const_literals_to_create_immutables: true

    # 4. ينبهك لو كتبت const في مكان براني وكان يغني عن كتابتها جوه (لتنظيف الكود)
    unnecessary_const: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
